# 뉴스 모아보기 홈피 만들기 2
## 1. 에러처리: try-catch
```js
// 6단계: 에러핸들링 - errorRender 함수 만들기 (error 났을 때 news-board 섹션에 그릴 페이지의 모습)
function  errorRender(message){
	let  errorHTML  =  `<div class="alert alert-danger text-center" role="alert">${message}</div>`
	document.getElementById("news-board").innerHTML  =  errorHTML
}
```    
errorRender을 코드 맨 마지막쪽에 만들놓으니까 화살표함수든 function을 이용한 함수정의든 모두 에러가 생겼다(비동기).. 그래서 어쩔 수 없이 이 함수를 코드 상단에 만들었다. 역시 아는만큼 보이나보다. 내부동작원리나 기본 이론이 얼마나 중요한지 알게 되었다.    
```js
const  getNews  =  async ()=>{
	try {
		let  header  =  new  Headers({'x-api-key':  '2j4Gs-jMBUua-gCAIUMb_Pz5U7UKkH3xteEp-QEMqqM'});
		let  response  =  await  fetch(url, {headers:  header}); 
		let  data  =  await  response.json();
		
		// 6단계: 에러핸들링.
		//1. 데이터 가져오는 단계에서 에러 발생시 response와 data에 어떤 변화가 생기는지 관찰한다.
		console.log("response:", response); //에러 발생시 response.status에서 에러코드를 알려준다 (ex.401 등)
		console.log("data", data); //에러 발생시 data.error_code와 data.message에서 에러에 관한 정보를 준다.

		//2. if-else로 에러 잡는다.
		if (response.status  ==  200) {
			if (data.total_hits  ==  0) { //검색창에 이상한 단어 검색했을 때 -> data.total_hits는 필터링된 데이터의 갯수임. 콘솔창에 들어가면 나옴.
				throw  new  Error("검색된 결과값이 없습니다.");
			}
			news  =  data.articles; //array형식임, data에서 article만 뽑아냄
			render();
		} else { //에러 나는 모든 상황
			throw  new  Error(data.message);
		}
	} catch (error) {
	errorRender(error.message);
	};
};
```  
- `throw new Error()`: 강제로 에러를 발생시킨다.
- `try`문에서 에러가 발생하면 코드가 종료되고 `catch`문으로 넘어간다.
